name: Build and Push to Docker Hub

on:
  push:
    branches:
      - dockerhubdeploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.MEDICAL_SYSTEM_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.MEDICAL_SYSTEM_DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:${{ github.sha }}
